// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v6.33.4
// source: services/legacy/peer_api/peer_api.proto

package peer_api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StreamInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamType uint32 `protobuf:"varint,1,opt,name=stream_type,json=streamType,proto3" json:"stream_type,omitempty"`
	BytesSent  uint64 `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesRecv  uint64 `protobuf:"varint,3,opt,name=bytes_recv,json=bytesRecv,proto3" json:"bytes_recv,omitempty"`
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{0}
}

func (x *StreamInfo) GetStreamType() uint32 {
	if x != nil {
		return x.StreamType
	}
	return 0
}

func (x *StreamInfo) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *StreamInfo) GetBytesRecv() uint64 {
	if x != nil {
		return x.BytesRecv
	}
	return 0
}

type Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr             string        `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	AddrLocal        string        `protobuf:"bytes,3,opt,name=addrLocal,proto3" json:"addrLocal,omitempty"`
	Services         string        `protobuf:"bytes,4,opt,name=services,proto3" json:"services,omitempty"`
	LastSend         int64         `protobuf:"varint,5,opt,name=lastSend,proto3" json:"lastSend,omitempty"`
	LastRecv         int64         `protobuf:"varint,6,opt,name=lastRecv,proto3" json:"lastRecv,omitempty"`
	SendSize         int64         `protobuf:"varint,7,opt,name=sendSize,proto3" json:"sendSize,omitempty"`
	RecvSize         int64         `protobuf:"varint,8,opt,name=recvSize,proto3" json:"recvSize,omitempty"`
	SendMemory       int64         `protobuf:"varint,9,opt,name=sendMemory,proto3" json:"sendMemory,omitempty"`
	PauseSend        bool          `protobuf:"varint,10,opt,name=pauseSend,proto3" json:"pauseSend,omitempty"`
	UnpauseSend      bool          `protobuf:"varint,11,opt,name=unpauseSend,proto3" json:"unpauseSend,omitempty"`
	BytesSent        uint64        `protobuf:"varint,12,opt,name=bytesSent,proto3" json:"bytesSent,omitempty"`
	BytesReceived    uint64        `protobuf:"varint,13,opt,name=bytesReceived,proto3" json:"bytesReceived,omitempty"`
	AvgRecvBandwidth int64         `protobuf:"varint,14,opt,name=avgRecvBandwidth,proto3" json:"avgRecvBandwidth,omitempty"`
	AssocId          string        `protobuf:"bytes,15,opt,name=assocId,proto3" json:"assocId,omitempty"`
	StreamPolicy     string        `protobuf:"bytes,16,opt,name=streamPolicy,proto3" json:"streamPolicy,omitempty"`
	Inbound          bool          `protobuf:"varint,17,opt,name=inbound,proto3" json:"inbound,omitempty"`
	ConnTime         int64         `protobuf:"varint,18,opt,name=connTime,proto3" json:"connTime,omitempty"`
	PingTime         int64         `protobuf:"varint,19,opt,name=pingTime,proto3" json:"pingTime,omitempty"`
	TimeOffset       int64         `protobuf:"varint,20,opt,name=timeOffset,proto3" json:"timeOffset,omitempty"`
	Version          uint32        `protobuf:"varint,21,opt,name=version,proto3" json:"version,omitempty"`
	SubVer           string        `protobuf:"bytes,22,opt,name=subVer,proto3" json:"subVer,omitempty"`
	StartingHeight   int32         `protobuf:"varint,23,opt,name=startingHeight,proto3" json:"startingHeight,omitempty"`
	CurrentHeight    int32         `protobuf:"varint,24,opt,name=currentHeight,proto3" json:"currentHeight,omitempty"`
	Banscore         int32         `protobuf:"varint,25,opt,name=banscore,proto3" json:"banscore,omitempty"`
	Whitelisted      bool          `protobuf:"varint,26,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	FeeFilter        int64         `protobuf:"varint,27,opt,name=feeFilter,proto3" json:"feeFilter,omitempty"`
	Streams          []*StreamInfo `protobuf:"bytes,28,rep,name=streams,proto3" json:"streams,omitempty"`
}

func (x *Peer) Reset() {
	*x = Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{1}
}

func (x *Peer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Peer) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Peer) GetAddrLocal() string {
	if x != nil {
		return x.AddrLocal
	}
	return ""
}

func (x *Peer) GetServices() string {
	if x != nil {
		return x.Services
	}
	return ""
}

func (x *Peer) GetLastSend() int64 {
	if x != nil {
		return x.LastSend
	}
	return 0
}

func (x *Peer) GetLastRecv() int64 {
	if x != nil {
		return x.LastRecv
	}
	return 0
}

func (x *Peer) GetSendSize() int64 {
	if x != nil {
		return x.SendSize
	}
	return 0
}

func (x *Peer) GetRecvSize() int64 {
	if x != nil {
		return x.RecvSize
	}
	return 0
}

func (x *Peer) GetSendMemory() int64 {
	if x != nil {
		return x.SendMemory
	}
	return 0
}

func (x *Peer) GetPauseSend() bool {
	if x != nil {
		return x.PauseSend
	}
	return false
}

func (x *Peer) GetUnpauseSend() bool {
	if x != nil {
		return x.UnpauseSend
	}
	return false
}

func (x *Peer) GetBytesSent() uint64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *Peer) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *Peer) GetAvgRecvBandwidth() int64 {
	if x != nil {
		return x.AvgRecvBandwidth
	}
	return 0
}

func (x *Peer) GetAssocId() string {
	if x != nil {
		return x.AssocId
	}
	return ""
}

func (x *Peer) GetStreamPolicy() string {
	if x != nil {
		return x.StreamPolicy
	}
	return ""
}

func (x *Peer) GetInbound() bool {
	if x != nil {
		return x.Inbound
	}
	return false
}

func (x *Peer) GetConnTime() int64 {
	if x != nil {
		return x.ConnTime
	}
	return 0
}

func (x *Peer) GetPingTime() int64 {
	if x != nil {
		return x.PingTime
	}
	return 0
}

func (x *Peer) GetTimeOffset() int64 {
	if x != nil {
		return x.TimeOffset
	}
	return 0
}

func (x *Peer) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Peer) GetSubVer() string {
	if x != nil {
		return x.SubVer
	}
	return ""
}

func (x *Peer) GetStartingHeight() int32 {
	if x != nil {
		return x.StartingHeight
	}
	return 0
}

func (x *Peer) GetCurrentHeight() int32 {
	if x != nil {
		return x.CurrentHeight
	}
	return 0
}

func (x *Peer) GetBanscore() int32 {
	if x != nil {
		return x.Banscore
	}
	return 0
}

func (x *Peer) GetWhitelisted() bool {
	if x != nil {
		return x.Whitelisted
	}
	return false
}

func (x *Peer) GetFeeFilter() int64 {
	if x != nil {
		return x.FeeFilter
	}
	return 0
}

func (x *Peer) GetStreams() []*StreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

type GetPeersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peers []*Peer `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetPeersResponse) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type GetPeerCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetPeerCountResponse) Reset() {
	*x = GetPeerCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeerCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerCountResponse) ProtoMessage() {}

func (x *GetPeerCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerCountResponse.ProtoReflect.Descriptor instead.
func (*GetPeerCountResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetPeerCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BanPeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr  string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Until int64  `protobuf:"varint,2,opt,name=until,proto3" json:"until,omitempty"`
}

func (x *BanPeerRequest) Reset() {
	*x = BanPeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPeerRequest) ProtoMessage() {}

func (x *BanPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPeerRequest.ProtoReflect.Descriptor instead.
func (*BanPeerRequest) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{4}
}

func (x *BanPeerRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *BanPeerRequest) GetUntil() int64 {
	if x != nil {
		return x.Until
	}
	return 0
}

type BanPeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *BanPeerResponse) Reset() {
	*x = BanPeerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BanPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanPeerResponse) ProtoMessage() {}

func (x *BanPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanPeerResponse.ProtoReflect.Descriptor instead.
func (*BanPeerResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{5}
}

func (x *BanPeerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UnbanPeerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *UnbanPeerRequest) Reset() {
	*x = UnbanPeerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbanPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPeerRequest) ProtoMessage() {}

func (x *UnbanPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPeerRequest.ProtoReflect.Descriptor instead.
func (*UnbanPeerRequest) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{6}
}

func (x *UnbanPeerRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type UnbanPeerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *UnbanPeerResponse) Reset() {
	*x = UnbanPeerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnbanPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanPeerResponse) ProtoMessage() {}

func (x *UnbanPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanPeerResponse.ProtoReflect.Descriptor instead.
func (*UnbanPeerResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{7}
}

func (x *UnbanPeerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type IsBannedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IpOrSubnet string `protobuf:"bytes,1,opt,name=ipOrSubnet,proto3" json:"ipOrSubnet,omitempty"`
}

func (x *IsBannedRequest) Reset() {
	*x = IsBannedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsBannedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBannedRequest) ProtoMessage() {}

func (x *IsBannedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBannedRequest.ProtoReflect.Descriptor instead.
func (*IsBannedRequest) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{8}
}

func (x *IsBannedRequest) GetIpOrSubnet() string {
	if x != nil {
		return x.IpOrSubnet
	}
	return ""
}

type IsBannedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsBanned bool `protobuf:"varint,1,opt,name=isBanned,proto3" json:"isBanned,omitempty"`
}

func (x *IsBannedResponse) Reset() {
	*x = IsBannedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsBannedResponse) ProtoMessage() {}

func (x *IsBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsBannedResponse.ProtoReflect.Descriptor instead.
func (*IsBannedResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{9}
}

func (x *IsBannedResponse) GetIsBanned() bool {
	if x != nil {
		return x.IsBanned
	}
	return false
}

type ListBannedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Banned []string `protobuf:"bytes,1,rep,name=banned,proto3" json:"banned,omitempty"`
}

func (x *ListBannedResponse) Reset() {
	*x = ListBannedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBannedResponse) ProtoMessage() {}

func (x *ListBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBannedResponse.ProtoReflect.Descriptor instead.
func (*ListBannedResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListBannedResponse) GetBanned() []string {
	if x != nil {
		return x.Banned
	}
	return nil
}

type ClearBannedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ClearBannedResponse) Reset() {
	*x = ClearBannedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClearBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBannedResponse) ProtoMessage() {}

func (x *ClearBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_legacy_peer_api_peer_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBannedResponse.ProtoReflect.Descriptor instead.
func (*ClearBannedResponse) Descriptor() ([]byte, []int) {
	return file_services_legacy_peer_api_peer_api_proto_rawDescGZIP(), []int{11}
}

func (x *ClearBannedResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_services_legacy_peer_api_peer_api_proto protoreflect.FileDescriptor

var file_services_legacy_peer_api_peer_api_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6c, 0x65, 0x67, 0x61, 0x63,
	0x79, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x6b, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x62, 0x79, 0x74, 0x65, 0x73, 0x53, 0x65, 0x6e, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x63, 0x76, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x09, 0x62, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x63, 0x76, 0x22, 0xe0, 0x06,
	0x0a, 0x04, 0x50, 0x65, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x64,
	0x64, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x64, 0x64, 0x72, 0x4c, 0x6f, 0x63, 0x61, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x6e, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x6e, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x63, 0x76, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x52, 0x65, 0x63, 0x76, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x6e, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x73, 0x65, 0x6e, 0x64, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x76,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x63, 0x76,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x75, 0x73, 0x65, 0x53, 0x65, 0x6e,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x61, 0x75, 0x73, 0x65, 0x53, 0x65,
	0x6e, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65, 0x53, 0x65, 0x6e,
	0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x75, 0x6e, 0x70, 0x61, 0x75, 0x73, 0x65,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x79, 0x74, 0x65, 0x73, 0x53, 0x65, 0x6e,
	0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x62, 0x79, 0x74, 0x65, 0x73, 0x53, 0x65,
	0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x62, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x61, 0x76, 0x67, 0x52,
	0x65, 0x63, 0x76, 0x42, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x10, 0x61, 0x76, 0x67, 0x52, 0x65, 0x63, 0x76, 0x42, 0x61, 0x6e, 0x64, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x49, 0x64, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x49, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x10,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x69, 0x6e, 0x67,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x13, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x69, 0x6e, 0x67,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x4f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x14, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x4f, 0x66,
	0x66, 0x73, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x75, 0x62, 0x56, 0x65, 0x72, 0x18, 0x16, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x75, 0x62, 0x56, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x69,
	0x6e, 0x67, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x17, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x24,
	0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x18, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x19, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x64, 0x18,
	0x1a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74,
	0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x65, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x1b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x65, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x12, 0x2e, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x1c, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73,
	0x22, 0x38, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x05, 0x70, 0x65, 0x65, 0x72, 0x73, 0x22, 0x2c, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x50, 0x65, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a, 0x0a, 0x0e, 0x42, 0x61, 0x6e, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x75,
	0x6e, 0x74, 0x69, 0x6c, 0x22, 0x21, 0x0a, 0x0f, 0x42, 0x61, 0x6e, 0x50, 0x65, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x26, 0x0a, 0x10, 0x55, 0x6e, 0x62, 0x61, 0x6e,
	0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22,
	0x23, 0x0a, 0x11, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x22, 0x31, 0x0a, 0x0f, 0x49, 0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x70, 0x4f, 0x72, 0x53,
	0x75, 0x62, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x70, 0x4f,
	0x72, 0x53, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x10, 0x49, 0x73, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x64, 0x22, 0x25, 0x0a, 0x13, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0xf6, 0x03, 0x0a,
	0x0b, 0x50, 0x65, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x08,
	0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1a, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40,
	0x0a, 0x07, 0x42, 0x61, 0x6e, 0x50, 0x65, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x65, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x42, 0x61, 0x6e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x42,
	0x61, 0x6e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x46, 0x0a, 0x09, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x50, 0x65, 0x65, 0x72, 0x12, 0x1a, 0x2e,
	0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x50, 0x65,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x65, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x08, 0x49, 0x73, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x49, 0x73, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x73, 0x42, 0x61, 0x6e,
	0x6e, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x1c, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x64, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1d, 0x2e, 0x70, 0x65, 0x65,
	0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x42, 0x61, 0x6e, 0x6e, 0x65,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x0c, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x1e, 0x2e, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x65, 0x65, 0x72,
	0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_legacy_peer_api_peer_api_proto_rawDescOnce sync.Once
	file_services_legacy_peer_api_peer_api_proto_rawDescData = file_services_legacy_peer_api_peer_api_proto_rawDesc
)

func file_services_legacy_peer_api_peer_api_proto_rawDescGZIP() []byte {
	file_services_legacy_peer_api_peer_api_proto_rawDescOnce.Do(func() {
		file_services_legacy_peer_api_peer_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_legacy_peer_api_peer_api_proto_rawDescData)
	})
	return file_services_legacy_peer_api_peer_api_proto_rawDescData
}

var file_services_legacy_peer_api_peer_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_services_legacy_peer_api_peer_api_proto_goTypes = []interface{}{
	(*StreamInfo)(nil),           // 0: peer_api.StreamInfo
	(*Peer)(nil),                 // 1: peer_api.Peer
	(*GetPeersResponse)(nil),     // 2: peer_api.GetPeersResponse
	(*GetPeerCountResponse)(nil), // 3: peer_api.GetPeerCountResponse
	(*BanPeerRequest)(nil),       // 4: peer_api.BanPeerRequest
	(*BanPeerResponse)(nil),      // 5: peer_api.BanPeerResponse
	(*UnbanPeerRequest)(nil),     // 6: peer_api.UnbanPeerRequest
	(*UnbanPeerResponse)(nil),    // 7: peer_api.UnbanPeerResponse
	(*IsBannedRequest)(nil),      // 8: peer_api.IsBannedRequest
	(*IsBannedResponse)(nil),     // 9: peer_api.IsBannedResponse
	(*ListBannedResponse)(nil),   // 10: peer_api.ListBannedResponse
	(*ClearBannedResponse)(nil),  // 11: peer_api.ClearBannedResponse
	(*emptypb.Empty)(nil),        // 12: google.protobuf.Empty
}
var file_services_legacy_peer_api_peer_api_proto_depIdxs = []int32{
	0,  // 0: peer_api.Peer.streams:type_name -> peer_api.StreamInfo
	1,  // 1: peer_api.GetPeersResponse.peers:type_name -> peer_api.Peer
	12, // 2: peer_api.PeerService.GetPeers:input_type -> google.protobuf.Empty
	4,  // 3: peer_api.PeerService.BanPeer:input_type -> peer_api.BanPeerRequest
	6,  // 4: peer_api.PeerService.UnbanPeer:input_type -> peer_api.UnbanPeerRequest
	8,  // 5: peer_api.PeerService.IsBanned:input_type -> peer_api.IsBannedRequest
	12, // 6: peer_api.PeerService.ListBanned:input_type -> google.protobuf.Empty
	12, // 7: peer_api.PeerService.ClearBanned:input_type -> google.protobuf.Empty
	12, // 8: peer_api.PeerService.GetPeerCount:input_type -> google.protobuf.Empty
	2,  // 9: peer_api.PeerService.GetPeers:output_type -> peer_api.GetPeersResponse
	5,  // 10: peer_api.PeerService.BanPeer:output_type -> peer_api.BanPeerResponse
	7,  // 11: peer_api.PeerService.UnbanPeer:output_type -> peer_api.UnbanPeerResponse
	9,  // 12: peer_api.PeerService.IsBanned:output_type -> peer_api.IsBannedResponse
	10, // 13: peer_api.PeerService.ListBanned:output_type -> peer_api.ListBannedResponse
	11, // 14: peer_api.PeerService.ClearBanned:output_type -> peer_api.ClearBannedResponse
	3,  // 15: peer_api.PeerService.GetPeerCount:output_type -> peer_api.GetPeerCountResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_services_legacy_peer_api_peer_api_proto_init() }
func file_services_legacy_peer_api_peer_api_proto_init() {
	if File_services_legacy_peer_api_peer_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_legacy_peer_api_peer_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeerCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanPeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BanPeerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnbanPeerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnbanPeerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsBannedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsBannedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBannedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_legacy_peer_api_peer_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClearBannedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_legacy_peer_api_peer_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_legacy_peer_api_peer_api_proto_goTypes,
		DependencyIndexes: file_services_legacy_peer_api_peer_api_proto_depIdxs,
		MessageInfos:      file_services_legacy_peer_api_peer_api_proto_msgTypes,
	}.Build()
	File_services_legacy_peer_api_peer_api_proto = out.File
	file_services_legacy_peer_api_peer_api_proto_rawDesc = nil
	file_services_legacy_peer_api_peer_api_proto_goTypes = nil
	file_services_legacy_peer_api_peer_api_proto_depIdxs = nil
}
