// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package blockvalidation_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// BlockValidationAPIClient is the client API for BlockValidationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlockValidationAPIClient interface {
	// Health returns the health of the API.
	HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error)
	BlockFound(ctx context.Context, in *BlockFoundRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	ProcessBlock(ctx context.Context, in *ProcessBlockRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	ValidateBlock(ctx context.Context, in *ValidateBlockRequest, opts ...grpc.CallOption) (*ValidateBlockResponse, error)
	RevalidateBlock(ctx context.Context, in *RevalidateBlockRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	GetCatchupStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*CatchupStatusResponse, error)
}

type blockValidationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBlockValidationAPIClient(cc grpc.ClientConnInterface) BlockValidationAPIClient {
	return &blockValidationAPIClient{cc}
}

func (c *blockValidationAPIClient) HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/blockvalidation_api.BlockValidationAPI/HealthGRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockValidationAPIClient) BlockFound(ctx context.Context, in *BlockFoundRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/blockvalidation_api.BlockValidationAPI/BlockFound", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockValidationAPIClient) ProcessBlock(ctx context.Context, in *ProcessBlockRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/blockvalidation_api.BlockValidationAPI/ProcessBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockValidationAPIClient) ValidateBlock(ctx context.Context, in *ValidateBlockRequest, opts ...grpc.CallOption) (*ValidateBlockResponse, error) {
	out := new(ValidateBlockResponse)
	err := c.cc.Invoke(ctx, "/blockvalidation_api.BlockValidationAPI/ValidateBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockValidationAPIClient) RevalidateBlock(ctx context.Context, in *RevalidateBlockRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/blockvalidation_api.BlockValidationAPI/RevalidateBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blockValidationAPIClient) GetCatchupStatus(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*CatchupStatusResponse, error) {
	out := new(CatchupStatusResponse)
	err := c.cc.Invoke(ctx, "/blockvalidation_api.BlockValidationAPI/GetCatchupStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlockValidationAPIServer is the server API for BlockValidationAPI service.
// All implementations must embed UnimplementedBlockValidationAPIServer
// for forward compatibility
type BlockValidationAPIServer interface {
	// Health returns the health of the API.
	HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error)
	BlockFound(context.Context, *BlockFoundRequest) (*EmptyMessage, error)
	ProcessBlock(context.Context, *ProcessBlockRequest) (*EmptyMessage, error)
	ValidateBlock(context.Context, *ValidateBlockRequest) (*ValidateBlockResponse, error)
	RevalidateBlock(context.Context, *RevalidateBlockRequest) (*EmptyMessage, error)
	GetCatchupStatus(context.Context, *EmptyMessage) (*CatchupStatusResponse, error)
	mustEmbedUnimplementedBlockValidationAPIServer()
}

// UnimplementedBlockValidationAPIServer must be embedded to have forward compatible implementations.
type UnimplementedBlockValidationAPIServer struct {
}

func (UnimplementedBlockValidationAPIServer) HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthGRPC not implemented")
}
func (UnimplementedBlockValidationAPIServer) BlockFound(context.Context, *BlockFoundRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockFound not implemented")
}
func (UnimplementedBlockValidationAPIServer) ProcessBlock(context.Context, *ProcessBlockRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessBlock not implemented")
}
func (UnimplementedBlockValidationAPIServer) ValidateBlock(context.Context, *ValidateBlockRequest) (*ValidateBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateBlock not implemented")
}
func (UnimplementedBlockValidationAPIServer) RevalidateBlock(context.Context, *RevalidateBlockRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevalidateBlock not implemented")
}
func (UnimplementedBlockValidationAPIServer) GetCatchupStatus(context.Context, *EmptyMessage) (*CatchupStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCatchupStatus not implemented")
}
func (UnimplementedBlockValidationAPIServer) mustEmbedUnimplementedBlockValidationAPIServer() {}

// UnsafeBlockValidationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlockValidationAPIServer will
// result in compilation errors.
type UnsafeBlockValidationAPIServer interface {
	mustEmbedUnimplementedBlockValidationAPIServer()
}

func RegisterBlockValidationAPIServer(s grpc.ServiceRegistrar, srv BlockValidationAPIServer) {
	s.RegisterService(&_BlockValidationAPI_serviceDesc, srv)
}

func _BlockValidationAPI_HealthGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockValidationAPIServer).HealthGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockvalidation_api.BlockValidationAPI/HealthGRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockValidationAPIServer).HealthGRPC(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockValidationAPI_BlockFound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockFoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockValidationAPIServer).BlockFound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockvalidation_api.BlockValidationAPI/BlockFound",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockValidationAPIServer).BlockFound(ctx, req.(*BlockFoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockValidationAPI_ProcessBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockValidationAPIServer).ProcessBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockvalidation_api.BlockValidationAPI/ProcessBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockValidationAPIServer).ProcessBlock(ctx, req.(*ProcessBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockValidationAPI_ValidateBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockValidationAPIServer).ValidateBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockvalidation_api.BlockValidationAPI/ValidateBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockValidationAPIServer).ValidateBlock(ctx, req.(*ValidateBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockValidationAPI_RevalidateBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevalidateBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockValidationAPIServer).RevalidateBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockvalidation_api.BlockValidationAPI/RevalidateBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockValidationAPIServer).RevalidateBlock(ctx, req.(*RevalidateBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlockValidationAPI_GetCatchupStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlockValidationAPIServer).GetCatchupStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blockvalidation_api.BlockValidationAPI/GetCatchupStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlockValidationAPIServer).GetCatchupStatus(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlockValidationAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blockvalidation_api.BlockValidationAPI",
	HandlerType: (*BlockValidationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthGRPC",
			Handler:    _BlockValidationAPI_HealthGRPC_Handler,
		},
		{
			MethodName: "BlockFound",
			Handler:    _BlockValidationAPI_BlockFound_Handler,
		},
		{
			MethodName: "ProcessBlock",
			Handler:    _BlockValidationAPI_ProcessBlock_Handler,
		},
		{
			MethodName: "ValidateBlock",
			Handler:    _BlockValidationAPI_ValidateBlock_Handler,
		},
		{
			MethodName: "RevalidateBlock",
			Handler:    _BlockValidationAPI_RevalidateBlock_Handler,
		},
		{
			MethodName: "GetCatchupStatus",
			Handler:    _BlockValidationAPI_GetCatchupStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/blockvalidation/blockvalidation_api/blockvalidation_api.proto",
}
