// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package subtreevalidation_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SubtreeValidationAPIClient is the client API for SubtreeValidationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubtreeValidationAPIClient interface {
	// HealthGRPC checks the service's health status.
	// It takes an empty request message and returns a response indicating the service's health.
	HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error)
	// CheckSubtreeFromBlock validates a subtree within a specified block in the blockchain.
	// It takes a request containing the subtree's merkle root hash and block details,
	// returning a response indicating the subtree's validity status.
	CheckSubtreeFromBlock(ctx context.Context, in *CheckSubtreeFromBlockRequest, opts ...grpc.CallOption) (*CheckSubtreeFromBlockResponse, error)
	CheckBlockSubtrees(ctx context.Context, in *CheckBlockSubtreesRequest, opts ...grpc.CallOption) (*CheckBlockSubtreesResponse, error)
}

type subtreeValidationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewSubtreeValidationAPIClient(cc grpc.ClientConnInterface) SubtreeValidationAPIClient {
	return &subtreeValidationAPIClient{cc}
}

func (c *subtreeValidationAPIClient) HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/subtreevalidation_api.SubtreeValidationAPI/HealthGRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subtreeValidationAPIClient) CheckSubtreeFromBlock(ctx context.Context, in *CheckSubtreeFromBlockRequest, opts ...grpc.CallOption) (*CheckSubtreeFromBlockResponse, error) {
	out := new(CheckSubtreeFromBlockResponse)
	err := c.cc.Invoke(ctx, "/subtreevalidation_api.SubtreeValidationAPI/CheckSubtreeFromBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subtreeValidationAPIClient) CheckBlockSubtrees(ctx context.Context, in *CheckBlockSubtreesRequest, opts ...grpc.CallOption) (*CheckBlockSubtreesResponse, error) {
	out := new(CheckBlockSubtreesResponse)
	err := c.cc.Invoke(ctx, "/subtreevalidation_api.SubtreeValidationAPI/CheckBlockSubtrees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubtreeValidationAPIServer is the server API for SubtreeValidationAPI service.
// All implementations must embed UnimplementedSubtreeValidationAPIServer
// for forward compatibility
type SubtreeValidationAPIServer interface {
	// HealthGRPC checks the service's health status.
	// It takes an empty request message and returns a response indicating the service's health.
	HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error)
	// CheckSubtreeFromBlock validates a subtree within a specified block in the blockchain.
	// It takes a request containing the subtree's merkle root hash and block details,
	// returning a response indicating the subtree's validity status.
	CheckSubtreeFromBlock(context.Context, *CheckSubtreeFromBlockRequest) (*CheckSubtreeFromBlockResponse, error)
	CheckBlockSubtrees(context.Context, *CheckBlockSubtreesRequest) (*CheckBlockSubtreesResponse, error)
	mustEmbedUnimplementedSubtreeValidationAPIServer()
}

// UnimplementedSubtreeValidationAPIServer must be embedded to have forward compatible implementations.
type UnimplementedSubtreeValidationAPIServer struct {
}

func (UnimplementedSubtreeValidationAPIServer) HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthGRPC not implemented")
}
func (UnimplementedSubtreeValidationAPIServer) CheckSubtreeFromBlock(context.Context, *CheckSubtreeFromBlockRequest) (*CheckSubtreeFromBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSubtreeFromBlock not implemented")
}
func (UnimplementedSubtreeValidationAPIServer) CheckBlockSubtrees(context.Context, *CheckBlockSubtreesRequest) (*CheckBlockSubtreesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBlockSubtrees not implemented")
}
func (UnimplementedSubtreeValidationAPIServer) mustEmbedUnimplementedSubtreeValidationAPIServer() {}

// UnsafeSubtreeValidationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubtreeValidationAPIServer will
// result in compilation errors.
type UnsafeSubtreeValidationAPIServer interface {
	mustEmbedUnimplementedSubtreeValidationAPIServer()
}

func RegisterSubtreeValidationAPIServer(s grpc.ServiceRegistrar, srv SubtreeValidationAPIServer) {
	s.RegisterService(&_SubtreeValidationAPI_serviceDesc, srv)
}

func _SubtreeValidationAPI_HealthGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtreeValidationAPIServer).HealthGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtreevalidation_api.SubtreeValidationAPI/HealthGRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtreeValidationAPIServer).HealthGRPC(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubtreeValidationAPI_CheckSubtreeFromBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSubtreeFromBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtreeValidationAPIServer).CheckSubtreeFromBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtreevalidation_api.SubtreeValidationAPI/CheckSubtreeFromBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtreeValidationAPIServer).CheckSubtreeFromBlock(ctx, req.(*CheckSubtreeFromBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubtreeValidationAPI_CheckBlockSubtrees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBlockSubtreesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtreeValidationAPIServer).CheckBlockSubtrees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtreevalidation_api.SubtreeValidationAPI/CheckBlockSubtrees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtreeValidationAPIServer).CheckBlockSubtrees(ctx, req.(*CheckBlockSubtreesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubtreeValidationAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "subtreevalidation_api.SubtreeValidationAPI",
	HandlerType: (*SubtreeValidationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthGRPC",
			Handler:    _SubtreeValidationAPI_HealthGRPC_Handler,
		},
		{
			MethodName: "CheckSubtreeFromBlock",
			Handler:    _SubtreeValidationAPI_CheckSubtreeFromBlock_Handler,
		},
		{
			MethodName: "CheckBlockSubtrees",
			Handler:    _SubtreeValidationAPI_CheckBlockSubtrees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/subtreevalidation/subtreevalidation_api/subtreevalidation_api.proto",
}
