// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v6.33.4
// source: services/subtreevalidation/subtreevalidation_api/subtreevalidation_api.proto

package subtreevalidation_api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// EmptyMessage represents an empty message structure used for health check requests.
type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{0}
}

// HealthResponse encapsulates the service health status information.
type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ok indicates if the service is operating normally
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// details provides additional context about the service health status
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	// timestamp records when the health check was performed
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CheckSubtreeFromBlockRequest defines the input parameters for subtree validation.
type CheckSubtreeFromBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// hash represents the merkle root hash of the subtree requiring validation
	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	// base_url specifies the endpoint for retrieving missing transaction data
	BaseUrl string `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// block_height indicates the blockchain height where the subtree is located
	BlockHeight uint32 `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// block_hash uniquely identifies the block containing the subtree
	BlockHash []byte `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// previous_block_hash identifies the block preceding the current block
	PreviousBlockHash []byte `protobuf:"bytes,5,opt,name=previous_block_hash,json=previousBlockHash,proto3" json:"previous_block_hash,omitempty"`
}

func (x *CheckSubtreeFromBlockRequest) Reset() {
	*x = CheckSubtreeFromBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSubtreeFromBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubtreeFromBlockRequest) ProtoMessage() {}

func (x *CheckSubtreeFromBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubtreeFromBlockRequest.ProtoReflect.Descriptor instead.
func (*CheckSubtreeFromBlockRequest) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{2}
}

func (x *CheckSubtreeFromBlockRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *CheckSubtreeFromBlockRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CheckSubtreeFromBlockRequest) GetBlockHeight() uint32 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *CheckSubtreeFromBlockRequest) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *CheckSubtreeFromBlockRequest) GetPreviousBlockHash() []byte {
	if x != nil {
		return x.PreviousBlockHash
	}
	return nil
}

// CheckSubtreeFromBlockResponse contains the validation result for a subtree check.
type CheckSubtreeFromBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// blessed indicates if the subtree passes all validation criteria
	Blessed bool `protobuf:"varint,1,opt,name=blessed,proto3" json:"blessed,omitempty"`
}

func (x *CheckSubtreeFromBlockResponse) Reset() {
	*x = CheckSubtreeFromBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSubtreeFromBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSubtreeFromBlockResponse) ProtoMessage() {}

func (x *CheckSubtreeFromBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSubtreeFromBlockResponse.ProtoReflect.Descriptor instead.
func (*CheckSubtreeFromBlockResponse) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{3}
}

func (x *CheckSubtreeFromBlockResponse) GetBlessed() bool {
	if x != nil {
		return x.Blessed
	}
	return false
}

// CheckBlockSubtreesRequest defines the input parameters for checking subtrees in a block.
type CheckBlockSubtreesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// block_hash identifies the block containing the subtrees to be checked
	Block []byte `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	// base_url specifies the endpoint for retrieving missing transaction data
	BaseUrl string `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	// peer_id is the P2P peer identifier used for peer reputation tracking
	PeerId string `protobuf:"bytes,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
}

func (x *CheckBlockSubtreesRequest) Reset() {
	*x = CheckBlockSubtreesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckBlockSubtreesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlockSubtreesRequest) ProtoMessage() {}

func (x *CheckBlockSubtreesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlockSubtreesRequest.ProtoReflect.Descriptor instead.
func (*CheckBlockSubtreesRequest) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{4}
}

func (x *CheckBlockSubtreesRequest) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *CheckBlockSubtreesRequest) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *CheckBlockSubtreesRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

// CheckBlockSubtreesResponse contains the validation results for subtrees in a block.
type CheckBlockSubtreesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// blessed indicates if all subtrees in the block pass validation
	Blessed bool `protobuf:"varint,1,opt,name=blessed,proto3" json:"blessed,omitempty"`
}

func (x *CheckBlockSubtreesResponse) Reset() {
	*x = CheckBlockSubtreesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckBlockSubtreesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlockSubtreesResponse) ProtoMessage() {}

func (x *CheckBlockSubtreesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlockSubtreesResponse.ProtoReflect.Descriptor instead.
func (*CheckBlockSubtreesResponse) Descriptor() ([]byte, []int) {
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP(), []int{5}
}

func (x *CheckBlockSubtreesResponse) GetBlessed() bool {
	if x != nil {
		return x.Blessed
	}
	return false
}

var File_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto protoreflect.FileDescriptor

var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc = []byte{
	0x0a, 0x4c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x75, 0x62, 0x74, 0x72,
	0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73, 0x75, 0x62,
	0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x70, 0x69, 0x2f, 0x73, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15,
	0x73, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x74, 0x0a, 0x0e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xbf, 0x01, 0x0a,
	0x1c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x46, 0x72, 0x6f,
	0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x2e,
	0x0a, 0x13, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x22, 0x39,
	0x0a, 0x1d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x6c, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x62, 0x6c, 0x65, 0x73, 0x73, 0x65, 0x64, 0x22, 0x65, 0x0a, 0x19, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x19, 0x0a, 0x08,
	0x62, 0x61, 0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x36, 0x0a, 0x1a, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x75,
	0x62, 0x74, 0x72, 0x65, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x62, 0x6c, 0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x62, 0x6c, 0x65, 0x73, 0x73, 0x65, 0x64, 0x32, 0xf6, 0x02, 0x0a, 0x14, 0x53, 0x75, 0x62,
	0x74, 0x72, 0x65, 0x65, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x50,
	0x49, 0x12, 0x5a, 0x0a, 0x0a, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x47, 0x52, 0x50, 0x43, 0x12,
	0x23, 0x2e, 0x73, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x25, 0x2e, 0x73, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x84, 0x01,
	0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x46, 0x72,
	0x6f, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x33, 0x2e, 0x73, 0x75, 0x62, 0x74, 0x72, 0x65,
	0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x46, 0x72, 0x6f, 0x6d,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x73,
	0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65,
	0x65, 0x46, 0x72, 0x6f, 0x6d, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x7b, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x53, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x73, 0x12, 0x30, 0x2e, 0x73, 0x75, 0x62,
	0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x75, 0x62,
	0x74, 0x72, 0x65, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x2e, 0x73,
	0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53,
	0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1a, 0x5a, 0x18, 0x2e, 0x2f, 0x3b, 0x73, 0x75, 0x62, 0x74, 0x72, 0x65, 0x65, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescOnce sync.Once
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData = file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc
)

func file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescGZIP() []byte {
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescOnce.Do(func() {
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData)
	})
	return file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDescData
}

var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_goTypes = []interface{}{
	(*EmptyMessage)(nil),                  // 0: subtreevalidation_api.EmptyMessage
	(*HealthResponse)(nil),                // 1: subtreevalidation_api.HealthResponse
	(*CheckSubtreeFromBlockRequest)(nil),  // 2: subtreevalidation_api.CheckSubtreeFromBlockRequest
	(*CheckSubtreeFromBlockResponse)(nil), // 3: subtreevalidation_api.CheckSubtreeFromBlockResponse
	(*CheckBlockSubtreesRequest)(nil),     // 4: subtreevalidation_api.CheckBlockSubtreesRequest
	(*CheckBlockSubtreesResponse)(nil),    // 5: subtreevalidation_api.CheckBlockSubtreesResponse
	(*timestamppb.Timestamp)(nil),         // 6: google.protobuf.Timestamp
}
var file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_depIdxs = []int32{
	6, // 0: subtreevalidation_api.HealthResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: subtreevalidation_api.SubtreeValidationAPI.HealthGRPC:input_type -> subtreevalidation_api.EmptyMessage
	2, // 2: subtreevalidation_api.SubtreeValidationAPI.CheckSubtreeFromBlock:input_type -> subtreevalidation_api.CheckSubtreeFromBlockRequest
	4, // 3: subtreevalidation_api.SubtreeValidationAPI.CheckBlockSubtrees:input_type -> subtreevalidation_api.CheckBlockSubtreesRequest
	1, // 4: subtreevalidation_api.SubtreeValidationAPI.HealthGRPC:output_type -> subtreevalidation_api.HealthResponse
	3, // 5: subtreevalidation_api.SubtreeValidationAPI.CheckSubtreeFromBlock:output_type -> subtreevalidation_api.CheckSubtreeFromBlockResponse
	5, // 6: subtreevalidation_api.SubtreeValidationAPI.CheckBlockSubtrees:output_type -> subtreevalidation_api.CheckBlockSubtreesResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_init() }
func file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_init() {
	if File_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSubtreeFromBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSubtreeFromBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckBlockSubtreesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckBlockSubtreesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_goTypes,
		DependencyIndexes: file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_depIdxs,
		MessageInfos:      file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_msgTypes,
	}.Build()
	File_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto = out.File
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_rawDesc = nil
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_goTypes = nil
	file_services_subtreevalidation_subtreevalidation_api_subtreevalidation_api_proto_depIdxs = nil
}
