// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package p2p_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PeerServiceClient is the client API for PeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerServiceClient interface {
	GetPeers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPeersResponse, error)
	BanPeer(ctx context.Context, in *BanPeerRequest, opts ...grpc.CallOption) (*BanPeerResponse, error)
	UnbanPeer(ctx context.Context, in *UnbanPeerRequest, opts ...grpc.CallOption) (*UnbanPeerResponse, error)
	IsBanned(ctx context.Context, in *IsBannedRequest, opts ...grpc.CallOption) (*IsBannedResponse, error)
	ListBanned(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBannedResponse, error)
	ClearBanned(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClearBannedResponse, error)
	AddBanScore(ctx context.Context, in *AddBanScoreRequest, opts ...grpc.CallOption) (*AddBanScoreResponse, error)
	ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error)
	DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerResponse, error)
	// Catchup metrics reporting endpoints
	RecordCatchupAttempt(ctx context.Context, in *RecordCatchupAttemptRequest, opts ...grpc.CallOption) (*RecordCatchupAttemptResponse, error)
	RecordCatchupSuccess(ctx context.Context, in *RecordCatchupSuccessRequest, opts ...grpc.CallOption) (*RecordCatchupSuccessResponse, error)
	RecordCatchupFailure(ctx context.Context, in *RecordCatchupFailureRequest, opts ...grpc.CallOption) (*RecordCatchupFailureResponse, error)
	RecordCatchupMalicious(ctx context.Context, in *RecordCatchupMaliciousRequest, opts ...grpc.CallOption) (*RecordCatchupMaliciousResponse, error)
	UpdateCatchupReputation(ctx context.Context, in *UpdateCatchupReputationRequest, opts ...grpc.CallOption) (*UpdateCatchupReputationResponse, error)
	UpdateCatchupError(ctx context.Context, in *UpdateCatchupErrorRequest, opts ...grpc.CallOption) (*UpdateCatchupErrorResponse, error)
	ResetReputation(ctx context.Context, in *ResetReputationRequest, opts ...grpc.CallOption) (*ResetReputationResponse, error)
	GetPeersForCatchup(ctx context.Context, in *GetPeersForCatchupRequest, opts ...grpc.CallOption) (*GetPeersForCatchupResponse, error)
	// Subtree and block validation reporting
	ReportValidSubtree(ctx context.Context, in *ReportValidSubtreeRequest, opts ...grpc.CallOption) (*ReportValidSubtreeResponse, error)
	ReportValidBlock(ctx context.Context, in *ReportValidBlockRequest, opts ...grpc.CallOption) (*ReportValidBlockResponse, error)
	// Peer status checking
	IsPeerMalicious(ctx context.Context, in *IsPeerMaliciousRequest, opts ...grpc.CallOption) (*IsPeerMaliciousResponse, error)
	IsPeerUnhealthy(ctx context.Context, in *IsPeerUnhealthyRequest, opts ...grpc.CallOption) (*IsPeerUnhealthyResponse, error)
	// Get full peer registry data with all metadata
	GetPeerRegistry(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPeerRegistryResponse, error)
	// Record bytes downloaded via HTTP from a peer
	RecordBytesDownloaded(ctx context.Context, in *RecordBytesDownloadedRequest, opts ...grpc.CallOption) (*RecordBytesDownloadedResponse, error)
	// Get single peer information by peer ID
	GetPeer(ctx context.Context, in *GetPeerRequest, opts ...grpc.CallOption) (*GetPeerResponse, error)
}

type peerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerServiceClient(cc grpc.ClientConnInterface) PeerServiceClient {
	return &peerServiceClient{cc}
}

func (c *peerServiceClient) GetPeers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/GetPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) BanPeer(ctx context.Context, in *BanPeerRequest, opts ...grpc.CallOption) (*BanPeerResponse, error) {
	out := new(BanPeerResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/BanPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) UnbanPeer(ctx context.Context, in *UnbanPeerRequest, opts ...grpc.CallOption) (*UnbanPeerResponse, error) {
	out := new(UnbanPeerResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/UnbanPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) IsBanned(ctx context.Context, in *IsBannedRequest, opts ...grpc.CallOption) (*IsBannedResponse, error) {
	out := new(IsBannedResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/IsBanned", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) ListBanned(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListBannedResponse, error) {
	out := new(ListBannedResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/ListBanned", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) ClearBanned(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClearBannedResponse, error) {
	out := new(ClearBannedResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/ClearBanned", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) AddBanScore(ctx context.Context, in *AddBanScoreRequest, opts ...grpc.CallOption) (*AddBanScoreResponse, error) {
	out := new(AddBanScoreResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/AddBanScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) ConnectPeer(ctx context.Context, in *ConnectPeerRequest, opts ...grpc.CallOption) (*ConnectPeerResponse, error) {
	out := new(ConnectPeerResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/ConnectPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) DisconnectPeer(ctx context.Context, in *DisconnectPeerRequest, opts ...grpc.CallOption) (*DisconnectPeerResponse, error) {
	out := new(DisconnectPeerResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/DisconnectPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) RecordCatchupAttempt(ctx context.Context, in *RecordCatchupAttemptRequest, opts ...grpc.CallOption) (*RecordCatchupAttemptResponse, error) {
	out := new(RecordCatchupAttemptResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/RecordCatchupAttempt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) RecordCatchupSuccess(ctx context.Context, in *RecordCatchupSuccessRequest, opts ...grpc.CallOption) (*RecordCatchupSuccessResponse, error) {
	out := new(RecordCatchupSuccessResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/RecordCatchupSuccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) RecordCatchupFailure(ctx context.Context, in *RecordCatchupFailureRequest, opts ...grpc.CallOption) (*RecordCatchupFailureResponse, error) {
	out := new(RecordCatchupFailureResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/RecordCatchupFailure", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) RecordCatchupMalicious(ctx context.Context, in *RecordCatchupMaliciousRequest, opts ...grpc.CallOption) (*RecordCatchupMaliciousResponse, error) {
	out := new(RecordCatchupMaliciousResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/RecordCatchupMalicious", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) UpdateCatchupReputation(ctx context.Context, in *UpdateCatchupReputationRequest, opts ...grpc.CallOption) (*UpdateCatchupReputationResponse, error) {
	out := new(UpdateCatchupReputationResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/UpdateCatchupReputation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) UpdateCatchupError(ctx context.Context, in *UpdateCatchupErrorRequest, opts ...grpc.CallOption) (*UpdateCatchupErrorResponse, error) {
	out := new(UpdateCatchupErrorResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/UpdateCatchupError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) ResetReputation(ctx context.Context, in *ResetReputationRequest, opts ...grpc.CallOption) (*ResetReputationResponse, error) {
	out := new(ResetReputationResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/ResetReputation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) GetPeersForCatchup(ctx context.Context, in *GetPeersForCatchupRequest, opts ...grpc.CallOption) (*GetPeersForCatchupResponse, error) {
	out := new(GetPeersForCatchupResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/GetPeersForCatchup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) ReportValidSubtree(ctx context.Context, in *ReportValidSubtreeRequest, opts ...grpc.CallOption) (*ReportValidSubtreeResponse, error) {
	out := new(ReportValidSubtreeResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/ReportValidSubtree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) ReportValidBlock(ctx context.Context, in *ReportValidBlockRequest, opts ...grpc.CallOption) (*ReportValidBlockResponse, error) {
	out := new(ReportValidBlockResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/ReportValidBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) IsPeerMalicious(ctx context.Context, in *IsPeerMaliciousRequest, opts ...grpc.CallOption) (*IsPeerMaliciousResponse, error) {
	out := new(IsPeerMaliciousResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/IsPeerMalicious", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) IsPeerUnhealthy(ctx context.Context, in *IsPeerUnhealthyRequest, opts ...grpc.CallOption) (*IsPeerUnhealthyResponse, error) {
	out := new(IsPeerUnhealthyResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/IsPeerUnhealthy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) GetPeerRegistry(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetPeerRegistryResponse, error) {
	out := new(GetPeerRegistryResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/GetPeerRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) RecordBytesDownloaded(ctx context.Context, in *RecordBytesDownloadedRequest, opts ...grpc.CallOption) (*RecordBytesDownloadedResponse, error) {
	out := new(RecordBytesDownloadedResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/RecordBytesDownloaded", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) GetPeer(ctx context.Context, in *GetPeerRequest, opts ...grpc.CallOption) (*GetPeerResponse, error) {
	out := new(GetPeerResponse)
	err := c.cc.Invoke(ctx, "/p2p_api.PeerService/GetPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServiceServer is the server API for PeerService service.
// All implementations must embed UnimplementedPeerServiceServer
// for forward compatibility
type PeerServiceServer interface {
	GetPeers(context.Context, *emptypb.Empty) (*GetPeersResponse, error)
	BanPeer(context.Context, *BanPeerRequest) (*BanPeerResponse, error)
	UnbanPeer(context.Context, *UnbanPeerRequest) (*UnbanPeerResponse, error)
	IsBanned(context.Context, *IsBannedRequest) (*IsBannedResponse, error)
	ListBanned(context.Context, *emptypb.Empty) (*ListBannedResponse, error)
	ClearBanned(context.Context, *emptypb.Empty) (*ClearBannedResponse, error)
	AddBanScore(context.Context, *AddBanScoreRequest) (*AddBanScoreResponse, error)
	ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error)
	DisconnectPeer(context.Context, *DisconnectPeerRequest) (*DisconnectPeerResponse, error)
	// Catchup metrics reporting endpoints
	RecordCatchupAttempt(context.Context, *RecordCatchupAttemptRequest) (*RecordCatchupAttemptResponse, error)
	RecordCatchupSuccess(context.Context, *RecordCatchupSuccessRequest) (*RecordCatchupSuccessResponse, error)
	RecordCatchupFailure(context.Context, *RecordCatchupFailureRequest) (*RecordCatchupFailureResponse, error)
	RecordCatchupMalicious(context.Context, *RecordCatchupMaliciousRequest) (*RecordCatchupMaliciousResponse, error)
	UpdateCatchupReputation(context.Context, *UpdateCatchupReputationRequest) (*UpdateCatchupReputationResponse, error)
	UpdateCatchupError(context.Context, *UpdateCatchupErrorRequest) (*UpdateCatchupErrorResponse, error)
	ResetReputation(context.Context, *ResetReputationRequest) (*ResetReputationResponse, error)
	GetPeersForCatchup(context.Context, *GetPeersForCatchupRequest) (*GetPeersForCatchupResponse, error)
	// Subtree and block validation reporting
	ReportValidSubtree(context.Context, *ReportValidSubtreeRequest) (*ReportValidSubtreeResponse, error)
	ReportValidBlock(context.Context, *ReportValidBlockRequest) (*ReportValidBlockResponse, error)
	// Peer status checking
	IsPeerMalicious(context.Context, *IsPeerMaliciousRequest) (*IsPeerMaliciousResponse, error)
	IsPeerUnhealthy(context.Context, *IsPeerUnhealthyRequest) (*IsPeerUnhealthyResponse, error)
	// Get full peer registry data with all metadata
	GetPeerRegistry(context.Context, *emptypb.Empty) (*GetPeerRegistryResponse, error)
	// Record bytes downloaded via HTTP from a peer
	RecordBytesDownloaded(context.Context, *RecordBytesDownloadedRequest) (*RecordBytesDownloadedResponse, error)
	// Get single peer information by peer ID
	GetPeer(context.Context, *GetPeerRequest) (*GetPeerResponse, error)
	mustEmbedUnimplementedPeerServiceServer()
}

// UnimplementedPeerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPeerServiceServer struct {
}

func (UnimplementedPeerServiceServer) GetPeers(context.Context, *emptypb.Empty) (*GetPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedPeerServiceServer) BanPeer(context.Context, *BanPeerRequest) (*BanPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BanPeer not implemented")
}
func (UnimplementedPeerServiceServer) UnbanPeer(context.Context, *UnbanPeerRequest) (*UnbanPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnbanPeer not implemented")
}
func (UnimplementedPeerServiceServer) IsBanned(context.Context, *IsBannedRequest) (*IsBannedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsBanned not implemented")
}
func (UnimplementedPeerServiceServer) ListBanned(context.Context, *emptypb.Empty) (*ListBannedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBanned not implemented")
}
func (UnimplementedPeerServiceServer) ClearBanned(context.Context, *emptypb.Empty) (*ClearBannedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearBanned not implemented")
}
func (UnimplementedPeerServiceServer) AddBanScore(context.Context, *AddBanScoreRequest) (*AddBanScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBanScore not implemented")
}
func (UnimplementedPeerServiceServer) ConnectPeer(context.Context, *ConnectPeerRequest) (*ConnectPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectPeer not implemented")
}
func (UnimplementedPeerServiceServer) DisconnectPeer(context.Context, *DisconnectPeerRequest) (*DisconnectPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisconnectPeer not implemented")
}
func (UnimplementedPeerServiceServer) RecordCatchupAttempt(context.Context, *RecordCatchupAttemptRequest) (*RecordCatchupAttemptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordCatchupAttempt not implemented")
}
func (UnimplementedPeerServiceServer) RecordCatchupSuccess(context.Context, *RecordCatchupSuccessRequest) (*RecordCatchupSuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordCatchupSuccess not implemented")
}
func (UnimplementedPeerServiceServer) RecordCatchupFailure(context.Context, *RecordCatchupFailureRequest) (*RecordCatchupFailureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordCatchupFailure not implemented")
}
func (UnimplementedPeerServiceServer) RecordCatchupMalicious(context.Context, *RecordCatchupMaliciousRequest) (*RecordCatchupMaliciousResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordCatchupMalicious not implemented")
}
func (UnimplementedPeerServiceServer) UpdateCatchupReputation(context.Context, *UpdateCatchupReputationRequest) (*UpdateCatchupReputationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCatchupReputation not implemented")
}
func (UnimplementedPeerServiceServer) UpdateCatchupError(context.Context, *UpdateCatchupErrorRequest) (*UpdateCatchupErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCatchupError not implemented")
}
func (UnimplementedPeerServiceServer) ResetReputation(context.Context, *ResetReputationRequest) (*ResetReputationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetReputation not implemented")
}
func (UnimplementedPeerServiceServer) GetPeersForCatchup(context.Context, *GetPeersForCatchupRequest) (*GetPeersForCatchupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeersForCatchup not implemented")
}
func (UnimplementedPeerServiceServer) ReportValidSubtree(context.Context, *ReportValidSubtreeRequest) (*ReportValidSubtreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportValidSubtree not implemented")
}
func (UnimplementedPeerServiceServer) ReportValidBlock(context.Context, *ReportValidBlockRequest) (*ReportValidBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportValidBlock not implemented")
}
func (UnimplementedPeerServiceServer) IsPeerMalicious(context.Context, *IsPeerMaliciousRequest) (*IsPeerMaliciousResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsPeerMalicious not implemented")
}
func (UnimplementedPeerServiceServer) IsPeerUnhealthy(context.Context, *IsPeerUnhealthyRequest) (*IsPeerUnhealthyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsPeerUnhealthy not implemented")
}
func (UnimplementedPeerServiceServer) GetPeerRegistry(context.Context, *emptypb.Empty) (*GetPeerRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeerRegistry not implemented")
}
func (UnimplementedPeerServiceServer) RecordBytesDownloaded(context.Context, *RecordBytesDownloadedRequest) (*RecordBytesDownloadedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordBytesDownloaded not implemented")
}
func (UnimplementedPeerServiceServer) GetPeer(context.Context, *GetPeerRequest) (*GetPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeer not implemented")
}
func (UnimplementedPeerServiceServer) mustEmbedUnimplementedPeerServiceServer() {}

// UnsafePeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerServiceServer will
// result in compilation errors.
type UnsafePeerServiceServer interface {
	mustEmbedUnimplementedPeerServiceServer()
}

func RegisterPeerServiceServer(s grpc.ServiceRegistrar, srv PeerServiceServer) {
	s.RegisterService(&_PeerService_serviceDesc, srv)
}

func _PeerService_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/GetPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).GetPeers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_BanPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).BanPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/BanPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).BanPeer(ctx, req.(*BanPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_UnbanPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).UnbanPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/UnbanPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).UnbanPeer(ctx, req.(*UnbanPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_IsBanned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsBannedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).IsBanned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/IsBanned",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).IsBanned(ctx, req.(*IsBannedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_ListBanned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).ListBanned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/ListBanned",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).ListBanned(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_ClearBanned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).ClearBanned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/ClearBanned",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).ClearBanned(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_AddBanScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBanScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).AddBanScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/AddBanScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).AddBanScore(ctx, req.(*AddBanScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_ConnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).ConnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/ConnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).ConnectPeer(ctx, req.(*ConnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_DisconnectPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).DisconnectPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/DisconnectPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).DisconnectPeer(ctx, req.(*DisconnectPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_RecordCatchupAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordCatchupAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).RecordCatchupAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/RecordCatchupAttempt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).RecordCatchupAttempt(ctx, req.(*RecordCatchupAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_RecordCatchupSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordCatchupSuccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).RecordCatchupSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/RecordCatchupSuccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).RecordCatchupSuccess(ctx, req.(*RecordCatchupSuccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_RecordCatchupFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordCatchupFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).RecordCatchupFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/RecordCatchupFailure",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).RecordCatchupFailure(ctx, req.(*RecordCatchupFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_RecordCatchupMalicious_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordCatchupMaliciousRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).RecordCatchupMalicious(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/RecordCatchupMalicious",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).RecordCatchupMalicious(ctx, req.(*RecordCatchupMaliciousRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_UpdateCatchupReputation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCatchupReputationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).UpdateCatchupReputation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/UpdateCatchupReputation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).UpdateCatchupReputation(ctx, req.(*UpdateCatchupReputationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_UpdateCatchupError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCatchupErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).UpdateCatchupError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/UpdateCatchupError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).UpdateCatchupError(ctx, req.(*UpdateCatchupErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_ResetReputation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetReputationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).ResetReputation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/ResetReputation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).ResetReputation(ctx, req.(*ResetReputationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_GetPeersForCatchup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeersForCatchupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).GetPeersForCatchup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/GetPeersForCatchup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).GetPeersForCatchup(ctx, req.(*GetPeersForCatchupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_ReportValidSubtree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportValidSubtreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).ReportValidSubtree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/ReportValidSubtree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).ReportValidSubtree(ctx, req.(*ReportValidSubtreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_ReportValidBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportValidBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).ReportValidBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/ReportValidBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).ReportValidBlock(ctx, req.(*ReportValidBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_IsPeerMalicious_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsPeerMaliciousRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).IsPeerMalicious(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/IsPeerMalicious",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).IsPeerMalicious(ctx, req.(*IsPeerMaliciousRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_IsPeerUnhealthy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsPeerUnhealthyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).IsPeerUnhealthy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/IsPeerUnhealthy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).IsPeerUnhealthy(ctx, req.(*IsPeerUnhealthyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_GetPeerRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).GetPeerRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/GetPeerRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).GetPeerRegistry(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_RecordBytesDownloaded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordBytesDownloadedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).RecordBytesDownloaded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/RecordBytesDownloaded",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).RecordBytesDownloaded(ctx, req.(*RecordBytesDownloadedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_GetPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).GetPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/p2p_api.PeerService/GetPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).GetPeer(ctx, req.(*GetPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PeerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "p2p_api.PeerService",
	HandlerType: (*PeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPeers",
			Handler:    _PeerService_GetPeers_Handler,
		},
		{
			MethodName: "BanPeer",
			Handler:    _PeerService_BanPeer_Handler,
		},
		{
			MethodName: "UnbanPeer",
			Handler:    _PeerService_UnbanPeer_Handler,
		},
		{
			MethodName: "IsBanned",
			Handler:    _PeerService_IsBanned_Handler,
		},
		{
			MethodName: "ListBanned",
			Handler:    _PeerService_ListBanned_Handler,
		},
		{
			MethodName: "ClearBanned",
			Handler:    _PeerService_ClearBanned_Handler,
		},
		{
			MethodName: "AddBanScore",
			Handler:    _PeerService_AddBanScore_Handler,
		},
		{
			MethodName: "ConnectPeer",
			Handler:    _PeerService_ConnectPeer_Handler,
		},
		{
			MethodName: "DisconnectPeer",
			Handler:    _PeerService_DisconnectPeer_Handler,
		},
		{
			MethodName: "RecordCatchupAttempt",
			Handler:    _PeerService_RecordCatchupAttempt_Handler,
		},
		{
			MethodName: "RecordCatchupSuccess",
			Handler:    _PeerService_RecordCatchupSuccess_Handler,
		},
		{
			MethodName: "RecordCatchupFailure",
			Handler:    _PeerService_RecordCatchupFailure_Handler,
		},
		{
			MethodName: "RecordCatchupMalicious",
			Handler:    _PeerService_RecordCatchupMalicious_Handler,
		},
		{
			MethodName: "UpdateCatchupReputation",
			Handler:    _PeerService_UpdateCatchupReputation_Handler,
		},
		{
			MethodName: "UpdateCatchupError",
			Handler:    _PeerService_UpdateCatchupError_Handler,
		},
		{
			MethodName: "ResetReputation",
			Handler:    _PeerService_ResetReputation_Handler,
		},
		{
			MethodName: "GetPeersForCatchup",
			Handler:    _PeerService_GetPeersForCatchup_Handler,
		},
		{
			MethodName: "ReportValidSubtree",
			Handler:    _PeerService_ReportValidSubtree_Handler,
		},
		{
			MethodName: "ReportValidBlock",
			Handler:    _PeerService_ReportValidBlock_Handler,
		},
		{
			MethodName: "IsPeerMalicious",
			Handler:    _PeerService_IsPeerMalicious_Handler,
		},
		{
			MethodName: "IsPeerUnhealthy",
			Handler:    _PeerService_IsPeerUnhealthy_Handler,
		},
		{
			MethodName: "GetPeerRegistry",
			Handler:    _PeerService_GetPeerRegistry_Handler,
		},
		{
			MethodName: "RecordBytesDownloaded",
			Handler:    _PeerService_RecordBytesDownloaded_Handler,
		},
		{
			MethodName: "GetPeer",
			Handler:    _PeerService_GetPeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/p2p/p2p_api/p2p_api.proto",
}
