// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package propagation_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PropagationAPIClient is the client API for PropagationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropagationAPIClient interface {
	// HealthGRPC checks the health status of the propagation service and its dependencies.
	// Returns a HealthResponse containing the service status and details.
	HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error)
	// ProcessTransaction processes a single BSV transaction.
	// The transaction must be provided in raw byte format and must be extended.
	// Coinbase transactions are not allowed.
	ProcessTransaction(ctx context.Context, in *ProcessTransactionRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	// ProcessTransactionBatch processes multiple transactions in a single request.
	// This is more efficient than processing transactions individually when dealing
	// with large numbers of transactions.
	ProcessTransactionBatch(ctx context.Context, in *ProcessTransactionBatchRequest, opts ...grpc.CallOption) (*ProcessTransactionBatchResponse, error)
}

type propagationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPropagationAPIClient(cc grpc.ClientConnInterface) PropagationAPIClient {
	return &propagationAPIClient{cc}
}

func (c *propagationAPIClient) HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/propagation_api.PropagationAPI/HealthGRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propagationAPIClient) ProcessTransaction(ctx context.Context, in *ProcessTransactionRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/propagation_api.PropagationAPI/ProcessTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propagationAPIClient) ProcessTransactionBatch(ctx context.Context, in *ProcessTransactionBatchRequest, opts ...grpc.CallOption) (*ProcessTransactionBatchResponse, error) {
	out := new(ProcessTransactionBatchResponse)
	err := c.cc.Invoke(ctx, "/propagation_api.PropagationAPI/ProcessTransactionBatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropagationAPIServer is the server API for PropagationAPI service.
// All implementations must embed UnimplementedPropagationAPIServer
// for forward compatibility
type PropagationAPIServer interface {
	// HealthGRPC checks the health status of the propagation service and its dependencies.
	// Returns a HealthResponse containing the service status and details.
	HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error)
	// ProcessTransaction processes a single BSV transaction.
	// The transaction must be provided in raw byte format and must be extended.
	// Coinbase transactions are not allowed.
	ProcessTransaction(context.Context, *ProcessTransactionRequest) (*EmptyMessage, error)
	// ProcessTransactionBatch processes multiple transactions in a single request.
	// This is more efficient than processing transactions individually when dealing
	// with large numbers of transactions.
	ProcessTransactionBatch(context.Context, *ProcessTransactionBatchRequest) (*ProcessTransactionBatchResponse, error)
	mustEmbedUnimplementedPropagationAPIServer()
}

// UnimplementedPropagationAPIServer must be embedded to have forward compatible implementations.
type UnimplementedPropagationAPIServer struct {
}

func (UnimplementedPropagationAPIServer) HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthGRPC not implemented")
}
func (UnimplementedPropagationAPIServer) ProcessTransaction(context.Context, *ProcessTransactionRequest) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTransaction not implemented")
}
func (UnimplementedPropagationAPIServer) ProcessTransactionBatch(context.Context, *ProcessTransactionBatchRequest) (*ProcessTransactionBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTransactionBatch not implemented")
}
func (UnimplementedPropagationAPIServer) mustEmbedUnimplementedPropagationAPIServer() {}

// UnsafePropagationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropagationAPIServer will
// result in compilation errors.
type UnsafePropagationAPIServer interface {
	mustEmbedUnimplementedPropagationAPIServer()
}

func RegisterPropagationAPIServer(s grpc.ServiceRegistrar, srv PropagationAPIServer) {
	s.RegisterService(&_PropagationAPI_serviceDesc, srv)
}

func _PropagationAPI_HealthGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropagationAPIServer).HealthGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/propagation_api.PropagationAPI/HealthGRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropagationAPIServer).HealthGRPC(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropagationAPI_ProcessTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropagationAPIServer).ProcessTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/propagation_api.PropagationAPI/ProcessTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropagationAPIServer).ProcessTransaction(ctx, req.(*ProcessTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PropagationAPI_ProcessTransactionBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessTransactionBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropagationAPIServer).ProcessTransactionBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/propagation_api.PropagationAPI/ProcessTransactionBatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropagationAPIServer).ProcessTransactionBatch(ctx, req.(*ProcessTransactionBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PropagationAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "propagation_api.PropagationAPI",
	HandlerType: (*PropagationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthGRPC",
			Handler:    _PropagationAPI_HealthGRPC_Handler,
		},
		{
			MethodName: "ProcessTransaction",
			Handler:    _PropagationAPI_ProcessTransaction_Handler,
		},
		{
			MethodName: "ProcessTransactionBatch",
			Handler:    _PropagationAPI_ProcessTransactionBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/propagation/propagation_api/propagation_api.proto",
}
